from PyQt5.QtGui import QFont


FONT_FAMILY_UI = "Bahnschrift"
FONT_FAMILY_FALLBACK = "Segoe UI"
FONT_FAMILY_MONO = "Consolas"

FONT_SIZE_TITLE = 25
FONT_SIZE_HERO = 25
FONT_SIZE_DISPLAY = 24
FONT_SIZE_XL = 20
FONT_SIZE_LARGE = 20
FONT_SIZE_MEDIUM = 18
FONT_SIZE_SMALL = 15
FONT_SIZE_CAPTION = 15
FONT_SIZE_MICRO = 14

WINDOW_MIN_WIDTH = 1280
WINDOW_MIN_HEIGHT = 800
WINDOW_DEFAULT_X = 80
WINDOW_DEFAULT_Y = 80
WINDOW_DEFAULT_WIDTH = 1440
WINDOW_DEFAULT_HEIGHT = 900

BUTTON_HEIGHT = 42
INPUT_HEIGHT = 42
TAB_HEIGHT = 40
SIDEBAR_BUTTON_HEIGHT = 56
TOPBAR_HEIGHT = 68
TOPBAR_STATUS_DOT = 10

RADIUS_LARGE = 14
RADIUS_MEDIUM = 10
RADIUS_SMALL = 8

PAGE_MARGIN = 24
PAGE_MARGIN_LARGE = 40
CARD_MARGIN = 20
CARD_MARGIN_COMPACT = 18
CARD_MARGIN_TIGHT = 14
SECTION_SPACING = 24
STACK_SPACING = 18
ITEM_SPACING = 12
COMPACT_SPACING = 8

SIDEBAR_WIDTH = 210
SIDEBAR_LOGO_HEIGHT = 94
SIDEBAR_ICON_WIDTH = 24

RIGHT_PANEL_WIDTH = 360
RIGHT_PANEL_INNER_MARGIN = 16
ALERT_CARD_MIN_HEIGHT = 100
ALERT_ICON_WIDTH = 14

DECODER_HEADER_HEIGHT = 72
DECODER_SEARCH_WIDTH = 220

CAN_FILTER_WIDTH = 160
CAN_SORT_WIDTH = 150
CAN_TABLE_ROW_HEIGHT = 42
CAN_COL_TIMESTAMP = 120
CAN_COL_ID = 85
CAN_COL_DLC = 55
CAN_COL_DATA = 220
CAN_COL_SIGNAL = 220

VISUALIZATION_MIN_HEIGHT = 260
VISUALIZATION_COMBO_WIDTH = 160

OVERLAY_MARGIN = 24
OVERLAY_CARD_MARGIN = 32
IMPORT_CARD_INNER_MARGIN = 14
IMPORT_CARD_MIN_WIDTH = 980
IMPORT_CARD_MIN_HEIGHT = 620
IMPORT_CARD_MAX_WIDTH = 1320
IMPORT_CARD_MAX_HEIGHT = 780

EXPORT_FILENAME_WIDTH = 360
EXPORT_CLOSE_BUTTON = 32
EXPORT_FOOTER_HEIGHT = 40
EXPORT_PREVIEW_BAR_HEIGHT = 5

SETTINGS_SAVE_WIDTH = 300
SETTINGS_COMBO_MIN_WIDTH = 280

INFO_BLOCK_VALUE_SIZE = 20
INFO_BLOCK_KEY_SIZE = 10
INFO_BLOCK_BAR_HEIGHT = 3
VALIDATION_LOG_HEIGHT = 120

PLACEHOLDER_ICON_SIZE = 56
PLACEHOLDER_TITLE_SIZE = 26
PLACEHOLDER_SUBTITLE_SIZE = 13

PLAYBACK_FONT_BUMP = 10
PLAYBACK_CAPTION = FONT_SIZE_CAPTION + PLAYBACK_FONT_BUMP
PLAYBACK_SMALL = FONT_SIZE_SMALL + PLAYBACK_FONT_BUMP
PLAYBACK_MEDIUM = FONT_SIZE_MEDIUM + PLAYBACK_FONT_BUMP
PLAYBACK_LARGE = FONT_SIZE_LARGE + PLAYBACK_FONT_BUMP
PLAYBACK_XL = FONT_SIZE_XL + PLAYBACK_FONT_BUMP
PLAYBACK_BAR_HEIGHT = 96
PLAYBACK_TABLE_ROW_HEIGHT = 56
PLAYBACK_SMALL_BUTTON = 38
PLAYBACK_PLAY_BUTTON = 52
PLAYBACK_SPEED_BUTTON_HEIGHT = 42
PLAYBACK_TABLE_COL_TIMESTAMP = 145
PLAYBACK_TABLE_COL_ID = 95
PLAYBACK_TABLE_COL_BUS = 72
PLAYBACK_TABLE_COL_LEN = 52
PLAYBACK_TABLE_COL_PAYLOAD = 280
PLAYBACK_TABLE_COL_RAW = 60
PLAYBACK_TABLE_COL_LABEL = 150


def app_font() -> QFont:
    font = QFont(FONT_FAMILY_UI, FONT_SIZE_LARGE)
    font.setStyleStrategy(QFont.PreferAntialias)
    return font


def mono_font(point_size: int = FONT_SIZE_MEDIUM, weight: int = QFont.Normal) -> QFont:
    font = QFont(FONT_FAMILY_MONO, point_size, weight)
    font.setStyleHint(QFont.TypeWriter)
    font.setStyleStrategy(QFont.PreferAntialias)
    return font
