This is makeindex, version 2.18 [MiKTeX 26.5].
Scanning style file ./build.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file build.acn....done (226 entries accepted, 0 rejected).
Sorting entries.....done (1940 comparisons).
Generating output file build.acr....done (140 lines written, 0 warnings).
Output written in build.acr.
Transcript written in build.alg.
